# Generated by Django 5.1.2 on 2024-11-21 12:32

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_loan_options_alter_requestloan_options_and_more'),
        ('payment_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentrepayment',
            options={'verbose_name': 'قسط', 'verbose_name_plural': 'قسط'},
        ),
        migrations.RenameField(
            model_name='installmentrepayment',
            old_name='pay_date',
            new_name='installment_due_date',
        ),
        migrations.RemoveField(
            model_name='installmentrepayment',
            name='User',
        ),
        migrations.RemoveField(
            model_name='installmentrepayment',
            name='loan',
        ),
        migrations.AddField(
            model_name='installmentrepayment',
            name='requested_loan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='borrow.requestloan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentrepayment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='installmentrepayment',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='installmentrepayment',
            name='upload_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
