# Generated by Django 5.1.2 on 2024-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_loan_options_alter_requestloan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestloan',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requestloan',
            name='status',
            field=models.CharField(choices=[('warning', 'درحال بررسی'), ('danger', 'رد شده'), ('success', 'تایید شده')], default='warning', max_length=50),
        ),
    ]
